#!/usr/bin/env python3
"""Generate documentation-ready source, complexity, coverage, and API metrics."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ElementTree
from collections import defaultdict
from pathlib import Path
from typing import Any, Iterable, Sequence


EXCLUDED_DIRECTORIES = (
    ".cache",
    ".git",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    ".venv",
    ".VSCodeCounter",
    "__pycache__",
    "build",
    "node_modules",
)
CPP_SUFFIXES = {
    ".c",
    ".cc",
    ".cpp",
    ".cxx",
    ".h",
    ".hh",
    ".hpp",
    ".hxx",
    ".inc",
    ".ipp",
    ".tpp",
}
COMPLEXITY_THRESHOLD = 10
FUNCTION_NLOC_THRESHOLD = 100
GENERATED_COMMENT = (
    "<!-- Automatically generated by scripts/generate-metrics.py; "
    "do not edit manually. -->"
)


class MetricsError(RuntimeError):
    """An actionable metrics-generation failure."""

    exit_code = 1


class MissingToolError(MetricsError):
    """A required metrics tool is not installed."""

    exit_code = 127


def parse_arguments() -> argparse.Namespace:
    """Parse the command-line interface."""

    parser = argparse.ArgumentParser(
        description=(
            "Generate Markdown reports and a JSON summary for the repository's "
            "code metrics."
        )
    )
    parser.add_argument(
        "--output-directory",
        required=True,
        type=Path,
        help="Destination below SOURCE_ROOT/build for generated reports.",
    )
    parser.add_argument(
        "--source-root",
        type=Path,
        help="Repository root (defaults to the parent of this script's directory).",
    )
    parser.add_argument(
        "--coverage-summary",
        type=Path,
        help="Optional gcovr JSON summary produced by make coverage.",
    )
    parser.add_argument(
        "--doxygen-xml",
        type=Path,
        help="Optional Doxygen XML directory or its index.xml file.",
    )
    return parser.parse_args()


def resolve_input_path(path: Path | None, invocation_directory: Path) -> Path | None:
    """Resolve a command-line input without requiring it to exist."""

    if path is None:
        return None
    if not path.is_absolute():
        path = invocation_directory / path
    return path.resolve()


def validate_paths(args: argparse.Namespace) -> tuple[Path, Path, Path | None, Path | None]:
    """Resolve paths and keep all generated output inside the build tree."""

    invocation_directory = Path.cwd()
    source_root = args.source_root or Path(__file__).resolve().parents[1]
    if not source_root.is_absolute():
        source_root = invocation_directory / source_root
    source_root = source_root.resolve()
    if not source_root.is_dir():
        raise MetricsError(f"source root is not a directory: {source_root}")

    output_directory = args.output_directory
    if not output_directory.is_absolute():
        output_directory = invocation_directory / output_directory
    output_directory = output_directory.resolve()
    build_directory = (source_root / "build").resolve()
    try:
        output_directory.relative_to(build_directory)
    except ValueError as error:
        raise MetricsError(
            "--output-directory must be inside the repository build directory "
            f"({build_directory})"
        ) from error

    coverage_summary = resolve_input_path(args.coverage_summary, invocation_directory)
    doxygen_xml = resolve_input_path(args.doxygen_xml, invocation_directory)
    return source_root, output_directory, coverage_summary, doxygen_xml


def relative_display_path(path: Path, source_root: Path) -> str:
    """Return a stable repository-relative path when possible."""

    try:
        return path.resolve().relative_to(source_root).as_posix()
    except ValueError:
        return path.as_posix()


def normalize_cloc_path(path: str) -> str:
    """Normalize cloc's platform-dependent relative paths."""

    normalized = path.replace("\\", "/")
    while normalized.startswith("./"):
        normalized = normalized[2:]
    return normalized


def integer(value: Any) -> int:
    """Convert a metrics value to an integer, treating missing values as zero."""

    if isinstance(value, bool):
        return int(value)
    if isinstance(value, (int, float)):
        return int(value)
    return 0


def number(value: Any) -> float | None:
    """Return a numeric value as a float."""

    if isinstance(value, bool):
        return float(value)
    if isinstance(value, (int, float)):
        return float(value)
    return None


def markdown_escape(value: Any) -> str:
    """Escape a value for use in a Markdown table cell."""

    return str(value).replace("|", "\\|").replace("\n", " ")


def markdown_code(value: Any) -> str:
    """Render a short value as inline Markdown code."""

    content = str(value).replace("\n", " ")
    delimiter_length = max(
        (len(match.group(0)) for match in re.finditer(r"`+", content)),
        default=0,
    ) + 1
    delimiter = "`" * delimiter_length
    padding = " " if content.startswith("`") or content.endswith("`") else ""
    return f"{delimiter}{padding}{content}{padding}{delimiter}"


def markdown_table(
    headers: Sequence[str],
    rows: Sequence[Sequence[Any]],
    *,
    numeric_columns: Iterable[int] = (),
) -> str:
    """Build a Markdown table with optional right-aligned columns."""

    if not rows:
        return "_No entries were found._"

    numeric = set(numeric_columns)
    header = "| " + " | ".join(headers) + " |"
    separator = "| " + " | ".join(
        "---:" if index in numeric else "---" for index in range(len(headers))
    ) + " |"
    body = [
        "| " + " | ".join(markdown_escape(value) for value in row) + " |"
        for row in rows
    ]
    return "\n".join([header, separator, *body])


def require_cloc() -> str:
    """Locate cloc or fail with installation guidance."""

    executable = shutil.which("cloc")
    if executable is None:
        raise MissingToolError(
            "cloc is required but was not found on PATH. Run 'make setup-native' "
            "or use the development container."
        )
    return executable


def load_lizard() -> tuple[Any, str]:
    """Import the Python lizard package or fail with installation guidance."""

    try:
        import lizard  # type: ignore[import-not-found]
        from lizard_ext import version as lizard_version  # type: ignore[import-not-found]
    except (ImportError, SystemExit) as error:
        raise MissingToolError(
            "the Python 'lizard' package is required by this interpreter. Run "
            "'make bootstrap' or use the development container."
        ) from error

    return lizard, str(lizard_version)


def collect_cloc(source_root: Path, executable: str) -> dict[str, Any]:
    """Collect language and per-file line counts from one cloc JSON run."""

    command = [
        executable,
        "--json",
        "--by-file",
        f"--exclude-dir={','.join(EXCLUDED_DIRECTORIES)}",
        ".",
    ]
    try:
        result = subprocess.run(
            command,
            cwd=source_root,
            capture_output=True,
            check=False,
            text=True,
        )
    except OSError as error:
        raise MetricsError(f"failed to run cloc: {error}") from error

    if result.returncode != 0:
        details = result.stderr.strip() or result.stdout.strip() or "no diagnostic output"
        raise MetricsError(f"cloc failed with exit code {result.returncode}: {details}")

    try:
        raw = json.loads(result.stdout)
    except json.JSONDecodeError as error:
        raise MetricsError(f"cloc produced invalid JSON: {error}") from error
    if not isinstance(raw, dict):
        raise MetricsError("cloc produced an unexpected JSON document")

    header = raw.get("header") if isinstance(raw.get("header"), dict) else {}
    files: list[dict[str, Any]] = []
    language_totals: defaultdict[str, dict[str, int]] = defaultdict(
        lambda: {"files": 0, "blank": 0, "comment": 0, "code": 0}
    )
    totals = {"files": 0, "blank": 0, "comment": 0, "code": 0}

    for raw_path, raw_stats in raw.items():
        if raw_path in {"header", "SUM"} or not isinstance(raw_stats, dict):
            continue
        language = str(raw_stats.get("language", "Unknown"))
        entry = {
            "path": normalize_cloc_path(str(raw_path)),
            "language": language,
            "blank": integer(raw_stats.get("blank")),
            "comment": integer(raw_stats.get("comment")),
            "code": integer(raw_stats.get("code")),
        }
        files.append(entry)
        language_totals[language]["files"] += 1
        totals["files"] += 1
        for metric in ("blank", "comment", "code"):
            language_totals[language][metric] += entry[metric]
            totals[metric] += entry[metric]

    files.sort(key=lambda entry: entry["path"].casefold())
    languages = [
        {"language": language, **stats}
        for language, stats in language_totals.items()
    ]
    languages.sort(key=lambda entry: (-entry["code"], entry["language"].casefold()))
    totals["lines"] = totals["blank"] + totals["comment"] + totals["code"]
    return {
        "tool_version": str(header.get("cloc_version", "unknown")),
        "totals": totals,
        "languages": languages,
        "files": files,
    }


def render_cloc_report(data: dict[str, Any]) -> str:
    """Render cloc data as a documentation fragment."""

    totals = data["totals"]
    total_table = markdown_table(
        ["Files", "Blank", "Comment", "Code", "All lines"],
        [[
            f"{totals['files']:,}",
            f"{totals['blank']:,}",
            f"{totals['comment']:,}",
            f"{totals['code']:,}",
            f"{totals['lines']:,}",
        ]],
        numeric_columns=range(5),
    )
    language_rows = [
        [
            entry["language"],
            f"{entry['files']:,}",
            f"{entry['blank']:,}",
            f"{entry['comment']:,}",
            f"{entry['code']:,}",
        ]
        for entry in data["languages"]
    ]
    file_rows = [
        [
            markdown_code(entry["path"]),
            entry["language"],
            f"{entry['blank']:,}",
            f"{entry['comment']:,}",
            f"{entry['code']:,}",
        ]
        for entry in data["files"]
    ]
    return "\n".join(
        [
            GENERATED_COMMENT,
            f"Generated with `cloc` {data['tool_version']}. Generated and dependency "
            "directories are excluded.",
            "",
            "#### Repository totals",
            "",
            total_table,
            "",
            "#### Lines by language",
            "",
            markdown_table(
                ["Language", "Files", "Blank", "Comment", "Code"],
                language_rows,
                numeric_columns={1, 2, 3, 4},
            ),
            "",
            "#### Lines by file",
            "",
            markdown_table(
                ["File", "Language", "Blank", "Comment", "Code"],
                file_rows,
                numeric_columns={2, 3, 4},
            ),
            "",
        ]
    )


def collect_complexity(
    source_root: Path,
    cloc_data: dict[str, Any],
    lizard: Any,
    lizard_version: str,
) -> dict[str, Any]:
    """Collect C and C++ file/function complexity with lizard's Python API."""

    source_paths = sorted(
        (
            source_root / entry["path"]
            for entry in cloc_data["files"]
            if Path(entry["path"]).suffix.lower() in CPP_SUFFIXES
        ),
        key=lambda path: path.as_posix().casefold(),
    )
    files: list[dict[str, Any]] = []
    functions: list[dict[str, Any]] = []

    for source_path in source_paths:
        try:
            source_path.resolve().relative_to(source_root)
        except ValueError as error:
            raise MetricsError(
                f"cloc reported a file outside the source root: {source_path}"
            ) from error
        if not source_path.is_file():
            continue

        try:
            file_information = lizard.analyze_file(str(source_path))
        except Exception as error:  # Lizard extensions may raise parser-specific errors.
            relative_path = relative_display_path(source_path, source_root)
            raise MetricsError(f"lizard failed while analyzing {relative_path}: {error}") from error

        relative_path = relative_display_path(source_path, source_root)
        file_functions: list[dict[str, Any]] = []
        for function in file_information.function_list:
            entry = {
                "file": relative_path,
                "name": str(getattr(function, "long_name", function.name)),
                "start_line": integer(function.start_line),
                "end_line": integer(function.end_line),
                "nloc": integer(function.nloc),
                "cyclomatic_complexity": integer(function.cyclomatic_complexity),
                "token_count": integer(function.token_count),
                "parameter_count": integer(function.parameter_count),
            }
            entry["length"] = max(0, entry["end_line"] - entry["start_line"] + 1)
            reasons = []
            if entry["cyclomatic_complexity"] > COMPLEXITY_THRESHOLD:
                reasons.append(f"CCN > {COMPLEXITY_THRESHOLD}")
            if entry["nloc"] > FUNCTION_NLOC_THRESHOLD:
                reasons.append(f"NLOC > {FUNCTION_NLOC_THRESHOLD}")
            entry["attention"] = reasons
            file_functions.append(entry)
            functions.append(entry)

        total_complexity = sum(
            function["cyclomatic_complexity"] for function in file_functions
        )
        function_count = len(file_functions)
        files.append(
            {
                "path": relative_path,
                "nloc": integer(file_information.nloc),
                "token_count": integer(file_information.token_count),
                "function_count": function_count,
                "total_cyclomatic_complexity": total_complexity,
                "average_cyclomatic_complexity": round(
                    total_complexity / function_count, 2
                ) if function_count else 0.0,
                "maximum_cyclomatic_complexity": max(
                    (
                        function["cyclomatic_complexity"]
                        for function in file_functions
                    ),
                    default=0,
                ),
            }
        )

    functions.sort(key=lambda entry: (entry["file"].casefold(), entry["start_line"]))
    total_complexity = sum(
        function["cyclomatic_complexity"] for function in functions
    )
    function_count = len(functions)
    summary = {
        "file_count": len(files),
        "function_count": function_count,
        "nloc": sum(file_entry["nloc"] for file_entry in files),
        "token_count": sum(file_entry["token_count"] for file_entry in files),
        "total_cyclomatic_complexity": total_complexity,
        "average_cyclomatic_complexity": round(
            total_complexity / function_count, 2
        ) if function_count else 0.0,
        "maximum_cyclomatic_complexity": max(
            (
                function["cyclomatic_complexity"]
                for function in functions
            ),
            default=0,
        ),
        "functions_requiring_attention": sum(
            bool(function["attention"]) for function in functions
        ),
    }
    return {
        "tool_version": lizard_version,
        "thresholds": {
            "cyclomatic_complexity": COMPLEXITY_THRESHOLD,
            "function_nloc": FUNCTION_NLOC_THRESHOLD,
        },
        "summary": summary,
        "files": files,
        "functions": functions,
    }


def render_complexity_report(data: dict[str, Any]) -> str:
    """Render lizard complexity data as a documentation fragment."""

    summary = data["summary"]
    summary_rows = [
        ["C/C++ files analyzed", f"{summary['file_count']:,}"],
        ["Functions analyzed", f"{summary['function_count']:,}"],
        ["Logical lines (NLOC)", f"{summary['nloc']:,}"],
        ["Total cyclomatic complexity", f"{summary['total_cyclomatic_complexity']:,}"],
        ["Average complexity per function", f"{summary['average_cyclomatic_complexity']:.2f}"],
        ["Maximum function complexity", f"{summary['maximum_cyclomatic_complexity']:,}"],
        ["Functions requiring attention", f"{summary['functions_requiring_attention']:,}"],
    ]
    file_rows = [
        [
            markdown_code(entry["path"]),
            f"{entry['function_count']:,}",
            f"{entry['nloc']:,}",
            f"{entry['total_cyclomatic_complexity']:,}",
            f"{entry['average_cyclomatic_complexity']:.2f}",
            f"{entry['maximum_cyclomatic_complexity']:,}",
        ]
        for entry in data["files"]
    ]
    ranked_functions = sorted(
        data["functions"],
        key=lambda entry: (
            -entry["cyclomatic_complexity"],
            -entry["nloc"],
            entry["file"].casefold(),
            entry["start_line"],
        ),
    )[:20]
    function_rows = [
        [
            markdown_code(entry["file"]),
            markdown_code(entry["name"]),
            f"{entry['start_line']}-{entry['end_line']}",
            f"{entry['nloc']:,}",
            f"{entry['cyclomatic_complexity']:,}",
            f"{entry['token_count']:,}",
            f"{entry['parameter_count']:,}",
        ]
        for entry in ranked_functions
    ]
    attention = [entry for entry in data["functions"] if entry["attention"]]
    attention_rows = [
        [
            markdown_code(entry["file"]),
            markdown_code(entry["name"]),
            f"{entry['start_line']}",
            f"{entry['nloc']:,}",
            f"{entry['cyclomatic_complexity']:,}",
            ", ".join(entry["attention"]),
        ]
        for entry in sorted(
            attention,
            key=lambda entry: (
                -entry["cyclomatic_complexity"],
                -entry["nloc"],
                entry["file"].casefold(),
            ),
        )
    ]
    return "\n".join(
        [
            GENERATED_COMMENT,
            f"Generated with Python `lizard` {data['tool_version']}. Cyclomatic "
            "complexity counts independent paths through each function; NLOC counts "
            "logical source lines.",
            "",
            "Thresholds are review indicators, not build gates: functions above "
            f"CCN {COMPLEXITY_THRESHOLD} or {FUNCTION_NLOC_THRESHOLD} NLOC are highlighted.",
            "",
            "#### Complexity summary",
            "",
            markdown_table(["Metric", "Value"], summary_rows, numeric_columns={1}),
            "",
            "#### Complexity by file",
            "",
            markdown_table(
                ["File", "Functions", "NLOC", "Total CCN", "Average CCN", "Maximum CCN"],
                file_rows,
                numeric_columns={1, 2, 3, 4, 5},
            ),
            "",
            "#### Most complex functions",
            "",
            "The table contains at most the 20 functions with the highest CCN; the JSON "
            "summary retains every function.",
            "",
            markdown_table(
                ["File", "Function", "Lines", "NLOC", "CCN", "Tokens", "Parameters"],
                function_rows,
                numeric_columns={2, 3, 4, 5, 6},
            ),
            "",
            "#### Functions requiring attention",
            "",
            markdown_table(
                ["File", "Function", "Line", "NLOC", "CCN", "Reason"],
                attention_rows,
                numeric_columns={2, 3, 4},
            ) if attention_rows else "No functions exceed the review thresholds.",
            "",
        ]
    )


def unavailable_section(kind: str, source: Path | None, message: str) -> dict[str, Any]:
    """Create a normalized unavailable optional-data section."""

    return {
        "available": False,
        "source": source.as_posix() if source is not None else None,
        "message": f"{kind} data unavailable. {message}",
    }


def coverage_metric(data: dict[str, Any], prefix: str) -> dict[str, Any]:
    """Normalize one gcovr coverage metric."""

    return {
        "covered": integer(data.get(f"{prefix}_covered")),
        "total": integer(data.get(f"{prefix}_total")),
        "percent": number(data.get(f"{prefix}_percent")),
    }


def collect_coverage(path: Path | None, source_root: Path) -> dict[str, Any]:
    """Read an optional gcovr JSON summary."""

    if path is None:
        return unavailable_section(
            "Coverage",
            None,
            "Pass --coverage-summary after running 'make coverage'.",
        )
    display_path = relative_display_path(path, source_root)
    if not path.is_file():
        return unavailable_section(
            "Coverage",
            Path(display_path),
            f"No summary was found at {display_path}. Run 'make coverage' first.",
        )

    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise MetricsError(f"could not read gcovr summary {display_path}: {error}") from error
    if not isinstance(raw, dict) or not isinstance(raw.get("files"), list):
        raise MetricsError(
            f"gcovr summary {display_path} does not contain the expected files array"
        )
    if not any(key in raw for key in ("line_total", "function_total", "branch_total")):
        raise MetricsError(
            f"gcovr summary {display_path} does not contain overall coverage totals"
        )

    files = []
    for raw_file in raw["files"]:
        if not isinstance(raw_file, dict):
            continue
        filename = normalize_cloc_path(str(raw_file.get("filename", "unknown")))
        files.append(
            {
                "path": filename,
                "lines": coverage_metric(raw_file, "line"),
                "functions": coverage_metric(raw_file, "function"),
                "branches": coverage_metric(raw_file, "branch"),
            }
        )
    files.sort(key=lambda entry: entry["path"].casefold())
    return {
        "available": True,
        "source": display_path,
        "format_version": str(raw.get("gcovr/summary_format_version", "unknown")),
        "totals": {
            "lines": coverage_metric(raw, "line"),
            "functions": coverage_metric(raw, "function"),
            "branches": coverage_metric(raw, "branch"),
        },
        "files": files,
    }


def format_coverage(metric: dict[str, Any]) -> str:
    """Format a normalized coverage metric."""

    percentage = metric.get("percent")
    if percentage is None:
        percent_text = "n/a"
    else:
        if percentage < 50.0:
            coverage_class = "coverage-pct--low"
        elif percentage < 80.0:
            coverage_class = "coverage-pct--medium"
        else:
            coverage_class = "coverage-pct--high"
        percent_text = (
            f'<span class="coverage-pct {coverage_class}">'
            f"{percentage:.1f}%</span>"
        )
    return f"{percent_text} ({metric['covered']:,}/{metric['total']:,})"


def render_coverage_report(data: dict[str, Any]) -> str:
    """Render coverage data or its useful placeholder."""

    if not data["available"]:
        return "\n".join([GENERATED_COMMENT, data["message"], ""])

    overall_rows = [
        [name.title(), format_coverage(data["totals"][name])]
        for name in ("lines", "functions", "branches")
    ]
    file_rows = [
        [
            markdown_code(entry["path"]),
            format_coverage(entry["lines"]),
            format_coverage(entry["functions"]),
            format_coverage(entry["branches"]),
        ]
        for entry in data["files"]
    ]
    return "\n".join(
        [
            GENERATED_COMMENT,
            f"Generated from gcovr summary {markdown_code(data['source'])} (format "
            f"{data['format_version']}).",
            "",
            "#### Overall test coverage",
            "",
            markdown_table(["Metric", "Coverage"], overall_rows, numeric_columns={1}),
            "",
            "#### Coverage by file",
            "",
            markdown_table(
                ["File", "Lines", "Functions", "Branches"],
                file_rows,
                numeric_columns={1, 2, 3},
            ),
            "",
        ]
    )


def xml_local_name(tag: str) -> str:
    """Remove an optional XML namespace from a tag."""

    return tag.rsplit("}", maxsplit=1)[-1]


def xml_child_text(element: ElementTree.Element, name: str) -> str:
    """Read a named direct XML child."""

    for child in element:
        if xml_local_name(child.tag) == name:
            return child.text or ""
    return ""


def collect_api(path: Path | None, source_root: Path) -> dict[str, Any]:
    """Read an optional Doxygen index.xml and summarize emitted symbols."""

    if path is None:
        return unavailable_section(
            "Doxygen API",
            None,
            "Pass --doxygen-xml after generating the Doxygen XML.",
        )
    index_path = path / "index.xml" if path.suffix.lower() != ".xml" else path
    display_path = relative_display_path(index_path, source_root)
    if not index_path.is_file():
        return unavailable_section(
            "Doxygen API",
            Path(display_path),
            f"No index was found at {display_path}. Run 'make docs' to generate it.",
        )

    try:
        root = ElementTree.parse(index_path).getroot()
    except (OSError, ElementTree.ParseError) as error:
        raise MetricsError(f"could not read Doxygen index {display_path}: {error}") from error
    if xml_local_name(root.tag) != "doxygenindex":
        raise MetricsError(
            f"Doxygen index {display_path} has unexpected root element {root.tag!r}"
        )

    compounds: list[dict[str, Any]] = []
    compounds_by_kind: defaultdict[str, int] = defaultdict(int)
    members_by_kind: defaultdict[str, int] = defaultdict(int)
    unique_members: set[str] = set()
    for compound_element in root:
        if xml_local_name(compound_element.tag) != "compound":
            continue
        kind = str(compound_element.get("kind", "unknown"))
        members = []
        for member_element in compound_element:
            if xml_local_name(member_element.tag) != "member":
                continue
            member_kind = str(member_element.get("kind", "unknown"))
            member_refid = str(member_element.get("refid", ""))
            members.append(
                {
                    "name": xml_child_text(member_element, "name"),
                    "kind": member_kind,
                    "refid": member_refid,
                }
            )
            unique_key = member_refid or (
                f"{kind}:{xml_child_text(compound_element, 'name')}:"
                f"{member_kind}:{xml_child_text(member_element, 'name')}"
            )
            if unique_key not in unique_members:
                unique_members.add(unique_key)
                members_by_kind[member_kind] += 1

        compounds.append(
            {
                "name": xml_child_text(compound_element, "name"),
                "kind": kind,
                "refid": str(compound_element.get("refid", "")),
                "member_count": len(members),
                "members": members,
            }
        )
        compounds_by_kind[kind] += 1

    compounds.sort(key=lambda entry: (entry["kind"], entry["name"].casefold()))
    return {
        "available": True,
        "source": display_path,
        "doxygen_version": str(root.get("version", "unknown")),
        "summary": {
            "compound_count": len(compounds),
            "member_count": len(unique_members),
            "compounds_by_kind": dict(sorted(compounds_by_kind.items())),
            "members_by_kind": dict(sorted(members_by_kind.items())),
        },
        "compounds": compounds,
    }


def render_api_report(data: dict[str, Any]) -> str:
    """Render Doxygen API metrics or their useful placeholder."""

    if not data["available"]:
        return "\n".join([GENERATED_COMMENT, data["message"], ""])

    summary = data["summary"]
    compound_kind_rows = [
        [kind, f"{count:,}"]
        for kind, count in summary["compounds_by_kind"].items()
    ]
    member_kind_rows = [
        [kind, f"{count:,}"]
        for kind, count in summary["members_by_kind"].items()
    ]
    compound_rows = [
        [
            markdown_code(entry["name"]),
            entry["kind"],
            f"{entry['member_count']:,}",
        ]
        for entry in data["compounds"]
    ]
    return "\n".join(
        [
            GENERATED_COMMENT,
            f"Generated from {markdown_code(data['source'])} with Doxygen "
            f"{data['doxygen_version']}. Counts describe symbols emitted to XML; they "
            "are not a documentation-completeness score.",
            "",
            "#### API totals",
            "",
            markdown_table(
                ["Metric", "Count"],
                [
                    ["Compounds", f"{summary['compound_count']:,}"],
                    ["Unique members", f"{summary['member_count']:,}"],
                ],
                numeric_columns={1},
            ),
            "",
            "#### Compounds by kind",
            "",
            markdown_table(["Kind", "Count"], compound_kind_rows, numeric_columns={1}),
            "",
            "#### Members by kind",
            "",
            markdown_table(["Kind", "Count"], member_kind_rows, numeric_columns={1}),
            "",
            "#### Doxygen compounds",
            "",
            markdown_table(
                ["Compound", "Kind", "Members"],
                compound_rows,
                numeric_columns={2},
            ),
            "",
        ]
    )


def write_text_atomically(path: Path, content: str) -> None:
    """Replace one generated text file without following a destination symlink."""

    temporary_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            newline="\n",
            prefix=f".{path.name}.",
            dir=path.parent,
            delete=False,
        ) as temporary_file:
            temporary_path = Path(temporary_file.name)
            temporary_file.write(content)
        temporary_path.chmod(0o644)
        os.replace(temporary_path, path)
        temporary_path = None
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


def write_reports(
    output_directory: Path,
    cloc_data: dict[str, Any],
    complexity_data: dict[str, Any],
    coverage_data: dict[str, Any],
    api_data: dict[str, Any],
) -> None:
    """Write all generated artifacts."""

    reports = {
        "cloc-report.md": render_cloc_report(cloc_data),
        "complexity-report.md": render_complexity_report(complexity_data),
        "coverage-report.md": render_coverage_report(coverage_data),
        "api-report.md": render_api_report(api_data),
    }
    summary = {
        "schema_version": 1,
        "tools": {
            "cloc": cloc_data["tool_version"],
            "lizard": complexity_data["tool_version"],
            "doxygen": api_data.get("doxygen_version")
            if api_data["available"] else None,
        },
        "cloc": cloc_data,
        "complexity": complexity_data,
        "coverage": coverage_data,
        "api": api_data,
    }
    reports["summary.json"] = (
        json.dumps(summary, indent=2, ensure_ascii=False) + "\n"
    )
    try:
        output_directory.mkdir(parents=True, exist_ok=True)
        for filename, content in reports.items():
            write_text_atomically(output_directory / filename, content)
    except OSError as error:
        raise MetricsError(f"could not write reports in {output_directory}: {error}") from error


def main() -> int:
    """Generate metrics and print a concise result summary."""

    try:
        args = parse_arguments()
        source_root, output_directory, coverage_path, doxygen_path = validate_paths(args)
        cloc_executable = require_cloc()
        lizard, lizard_version = load_lizard()

        cloc_data = collect_cloc(source_root, cloc_executable)
        complexity_data = collect_complexity(
            source_root, cloc_data, lizard, lizard_version
        )
        coverage_data = collect_coverage(coverage_path, source_root)
        api_data = collect_api(doxygen_path, source_root)
        write_reports(
            output_directory,
            cloc_data,
            complexity_data,
            coverage_data,
            api_data,
        )
    except MetricsError as error:
        print(f"metrics: error: {error}", file=sys.stderr)
        return error.exit_code

    coverage_status = "available" if coverage_data["available"] else "unavailable"
    api_status = "available" if api_data["available"] else "unavailable"
    print(
        "Metrics generated in "
        f"{relative_display_path(output_directory, source_root)}: "
        f"{cloc_data['totals']['files']} files, "
        f"{cloc_data['totals']['code']} code lines, "
        f"{complexity_data['summary']['function_count']} C/C++ functions; "
        f"coverage {coverage_status}; Doxygen API {api_status}."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
